import Head from 'next/head';
import Image from 'next/image'
import Style from '../../frontend/style.css';
import { Row, Col } from "reactstrap";
export default function Pokemon() {
return (
<div>
  <Head>
    <title>Pokemon home page</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"/>
    <link rel="stylesheet" href={Style}/>
  </Head>
  <header>
    
  </header>
  <main>
   
      <section className="section1">
      <div className="container">
      <div className="p-4 logo d-flex justify-content-center align-items-center">
        <img src="/asset/Logo.png" className="img-fluid" alt=""/>
      </div>
        
      </div>
        
        
        
      </section>
      <section className="section2">
        <div className="description-container  mx-3">
          <div className="description  position-absolute px-5 mx-5" style={{zIndex: '1'}}>
          <div className="description-title d-flex justify-content-center align-items-center ">
            <img src="/asset/Brush.png" className="img-fluid" alt=""/>
            <h1 className="p-4 text-center text-primary fw-bold">Ash & Pikachu Arrive in <br/> Pokemon Universe</h1>
          </div>
          <div className="description-box position-relative d-flex ustify-content-center align-items-center">
            <div className="container">
            
              <Row>
              <Col md="8" className="pe-0">
              <Row>
              <Col md="8" className="">
              <Row>
              <Col md="12" >
              Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              specimen book. It has survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged.
              </Col>
              </Row>
              </Col>
              <Col md="4" className="px-4 d-flex justify-content-center align-items-center" style={{marginTop:'90px'}}>
              <img src="/asset/Image03.png" className="img-fluid" alt=""/>
              </Col>
              </Row>
              <Row>
              <Col md="8">
              <Row>
              <Col md="8" className="py-2">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              specimen book. It has survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged.
              </Col>
              <Col md="4" className="py-3 pe-0 ps-4">
              <img src="/asset/Image04.png" className="img-fluid" alt=""/>
              </Col>
              </Row>
              </Col>
              
              <Col md="4" className="px-4  d-flex justify-content-center align-items-center" style={{marginTop:'185px'}}>
              <img src="/asset/Image02.png" className="img-fluid" alt=""/>
              </Col>
              </Row>
              <Row>
              <Col md="12" className="py-5 mt-5">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              specimen book. It has survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged.Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              specimen book. It has survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged.
              </Col>
              
              </Row>
              </Col>
              <Col md="4" className="ps-0 ">
              
              <Row>
                <Col md="12" className="ps-0">
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type 
                </Col>
              </Row>
              <Row>
                <Col md="6" className="ps-0 pe-0">
                  <img src="/asset/Image05.png" className="img-fluid" alt=""/>
                </Col>
                <Col md="6" className="ps-0 pe-0">
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              
                </Col>
              </Row>
              <Row>
                <Col md="6" className="ps-0 pe-0">
                  <img src="/asset/Image01.png" className="img-fluid" alt=""/>
                </Col>
                <Col md="6" className="ps-0 pe-0">
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type
              
                </Col>
              </Row>
              <Row>
                <Col md="12">
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry
              . Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and 
                </Col>
              </Row>
              </Col>
              </Row>
             
            </div>
          </div>
          
        </div>
        </div>
        <div className="d-flex justify-content-between position-relative" style={{zIndex:"-1"}}>
          <Image
          className="p-0 img-fluid"
          src="/asset/Left.png"
          alt="bg"
          width="100"
          height="500"
          />
          <Image
          className="img-fluid"
          src="/asset/Left.png"
          alt="bg"
          width="100"
          height="500"
          />
        </div>
      </section>
      
    
  </main>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</div>
);
}